import type { Metadata } from "next";

import "@/styles/globals.css";
import { gilroy } from "@/libs/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable} ${gilroy.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
